name: build-clang-llm 

on:
  workflow_dispatch:

#env:
#  PKGDEST: "/tmp/pkgbuild-llvm-git"

jobs:
  build:
    runs-on: ubuntu-latest
#    container: archlinux:latest 
    steps:
      - name: Checkount repo
        uses: actions/checkout@v4
      - name: Prepare for makepkg
        run: |
          git clone --depth 1 https://gitlab.archlinux.org/archlinux/packaging/packages/compiler-rt.git
          sed -i 's/pkgver=17.0.6/pkgver=18.1.0/g' compiler-rt/PKGBUILD
          sed -i 's/11b8d09dcf92a0f91c5c82defb5ad9ff4acf5cf073a80c317204baa922d136b4/SKIP/g' compiler-rt/PKGBUILD
          sed -i 's/807f069c54dc20cb47b21c1f6acafdd9c649f3ae015609040d6182cab01140f4/SKIP/g' compiler-rt/PKGBUILD
          git clone --depth 1 https://gitlab.archlinux.org/archlinux/packaging/packages/clang.git
          sed -i 's/pkgver=17.0.6/pkgver=18.1.0/g' clang/PKGBUILD
          sed -i 's/a78f668a726ae1d3d9a7179996d97b12b90fb76ab9442a43110b972ff7ad9029/SKIP/g' clang/PKGBUILD
          sed -i 's/aa774642415d338d7b77a66fcbad6fd1f77f382dabcb67422a6230614eff1ab9/SKIP/g' clang/PKGBUILD
          sed -i 's/b638167da139126ca11917b6880207cc6e8f9d1cbb1a48d87d017f697ef78188/SKIP/g' clang/PKGBUILD
          sed -i 's/807f069c54dc20cb47b21c1f6acafdd9c649f3ae015609040d6182cab01140f4/SKIP/g' clang/PKGBUILD
          sed -i 's/3054d0a9c9375dab1a4539cc2cc45ab340341c5d71475f9599ba7752e222947b/SKIP/g' clang/PKGBUILD
          sed -i '/patch -Np2/d' clang/PKGBUILD
          sed -i '/clang-tools-extra|clang/d' clang/PKGBUILD
          git clone --depth 1 https://gitlab.archlinux.org/archlinux/packaging/packages/lld.git
          sed -i 's/pkgver=17.0.6/pkgver=18.1.0/g' lld/PKGBUILD
          sed -i 's/4ac13125616dc44905b85820aa403d27ec1226329b7f674daeb5f5584c6f0b22/SKIP/g' lld/PKGBUILD
          sed -i 's/b638167da139126ca11917b6880207cc6e8f9d1cbb1a48d87d017f697ef78188/SKIP/g' lld/PKGBUILD
          sed -i 's/9e7535a353aa862730b4ba38df42e06f6856b40c4cc51b57f27b5046dc21d70d/SKIP/g' lld/PKGBUILD
          sed -i 's/807f069c54dc20cb47b21c1f6acafdd9c649f3ae015609040d6182cab01140f4/SKIP/g' lld/PKGBUILD
          sed -i '/patch -Np2/d' lld/PKGBUILD
          gh run download -n llvm-git
          ls -lh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set UserID
        run: |
          echo "USERID=$(id -u $(whoami))" >> $GITHUB_ENV
        env: 
          USERID: ''
      - name: Build 
        uses: docker://archlinux:latest
        with:
          entrypoint: '/bin/sh'
          args: ./build-clang_lld.sh ${{ env.USERID }}
#      - name: Upload packages
#        uses: actions/upload-artifact@v4
#        with:
#          name: llvm-git
#          path: ${{ github.workspace }}/llvm-git/*.pkg.tar.zst
