name: create-archive

on:
  workflow_run:
    workflows:
      - llvm-build-clang2
    branches:
      - main
    types: 
      - completed
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkount repo
        uses: actions/checkout@v4
      - name: Get artifacts
        run: |
          gh run download -n llvm-libs
          gh run download -n compiler-rt
          gh run download -n clang
          gh run download -n lld
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: llvm
          path: ${{ github.workspace }}/*.pkg.tar.zst
