name: gcc-build-compiler-rt

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup
        run: |
          docker images
          sudo rm -rf "/opt/*" || true
          sudo rm -rf "/usr/share/dotnet" || true
          sudo rm -rf "$AGENT_TOOLSDIRECTORY" || true
          sudo rm -rf "/usr/local/lib/android" || true
          sudo rm -rf "/usr/local/share/boost" || true
          sudo rm -rf "/usr/lib/jvm" || true
          sudo rm -rf "/usr/share/swift" || true
          sudo rm -rf "/usr/local/julia*" || true
          sudo rm -rf "/usr/share/kotlinc" || true
          sudo rm -rf "/usr/local/share/edge_driver" || true
          sudo rm -rf "/usr/local/share/chromedriver-linux64" || true
          sudo rm -rf "/usr/local/share/gecko_driver" || true
          sudo rm -rf "/usr/share/miniconda" || true
          sudo rm -rf "/usr/local/share/phantomjs*" || true
          sudo rm -rf "/usr/share/sbt" || true
          sudo rm -rf "/usr/local/sqlpackage" || true
          docker rmi $(docker image ls -q --filter "reference=node*")
          docker rmi $(docker image ls -q --filter "reference=debian*")
          docker rmi $(docker image ls -q --filter "reference=alpine*")
          docker rmi $(docker image ls -q --filter "reference=ubuntu:20.04")
          sudo npm uninstall bazel
          rustup self uninstall -y
          sudo apt purge \
            ansible \
            apache2 \
            aria2 \
            azure-cli \
            cabal* \
            clang* \
            dotnet-sdk* \
            firefox \
            ghc* \
            google-chrome-stable \
            google-cloud-sdk \
            kubectl \
            libpq-dev \
            microsoft-edge-stable \
            moby-buildx \
            moby-cli \
            moby-compose \
            moby-engine \
            mongodb* \
            mono-complete \
            mysql* \
            nginx \
            node* \
            npm* \
            nuget \
            php* \
            postgresql* \
            powershell \
            r-base \
            rpm \
            ruby* \
            sphinxsearch \
            subversion \
            yarn \
            -yq >/dev/null 2>&1 || true
          sudo apt-get autoremove -y >/dev/null 2>&1 || true
          sudo apt-get autoclean -y >/dev/null 2>&1 || true
          df -h
      - name: Checkount repo
        uses: actions/checkout@v4
      - name: Prepare for makepkg
        run: |
          git clone --depth 1 https://gitlab.archlinux.org/archlinux/packaging/packages/compiler-rt.git
          sed -i 's/pkgver=17.0.6/pkgver=18.1.3/g' compiler-rt/PKGBUILD
          sed -i 's/11b8d09dcf92a0f91c5c82defb5ad9ff4acf5cf073a80c317204baa922d136b4/SKIP/g' compiler-rt/PKGBUILD
          sed -i 's/807f069c54dc20cb47b21c1f6acafdd9c649f3ae015609040d6182cab01140f4/SKIP/g' compiler-rt/PKGBUILD
          git clone --depth 1 https://gitlab.archlinux.org/archlinux/packaging/packages/clang.git
          echo "USERID=$(id -u $(whoami))" >> $GITHUB_ENV
          gh run download -n llvm-gcc
          pacman --noconfirm -U llvm-*.zst
          rm llvm-*.zst
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERID: ''
      - name: Build compiler-rt
        uses: docker://archlinux:latest
        with:
          entrypoint: '/bin/sh'
          args: ./build.sh ${{ env.USERID }}
      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: compiler-rt-gcc
          path: ${{ github.workspace }}/*.pkg.tar.zst
