name: gcc-build-lld

on:
  workflow_run:
    workflows:
      - gcc-build-clang
    branches:
      - main
    types: 
      - completed
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkount repo
        uses: actions/checkout@v4
      - name: Prepare for makepkg
        run: |
          git clone --depth 1 https://gitlab.archlinux.org/archlinux/packaging/packages/lld.git
          sh ./modify-lld-pkgbuild.sh
          echo "USERID=$(id -u $(whoami))" >> $GITHUB_ENV
          gh run download -n llvm-libs-gcc
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERID: ''
      - name: Build lld
        uses: docker://archlinux:latest
        with:
          entrypoint: '/bin/sh'
          args: ./gcc-build-lld.sh ${{ env.USERID }}
      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: lld-gcc
          path: ${{ github.workspace }}/*.pkg.tar.zst
