name: llvm-git

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 13
      - name: Checkount repo
        uses: actions/checkout@v4
      - name: Cleanup
        run: |
          sh ./cleanup.sh
      - name: Prepare for makepkg
        run: |
          git clone --depth 1 https://aur.archlinux.org/llvm-git.git
          sed -i 's/llvm-project.git/llvm-project.git#tag=llvmorg-18.1.4/g' llvm-git/PKGBUILD
          echo "USERID=$(id -u $(whoami))" >> $GITHUB_ENV
#          sed -i 's/polly;lldb;lld;/lld;/g' llvm-git/PKGBUILD
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERID: ''    
      - name: Build llvm
        uses: docker://archlinux:latest
        with:
          entrypoint: '/bin/sh'
          args: ./llvm-git.sh ${{ env.USERID }}
      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: llvm
          path: ${{ github.workspace }}/*.pkg.tar.zst
