name: llvm-build

on:
  workflow_dispatch:
    inputs:
      new_llvm_ver:
        type: string
        required: false
        description: "New LLVM version"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 13
      - name: Checkount repo
        uses: actions/checkout@v4
      - name: Cleanup
        run: |
          sh ./cleanup.sh
      - name: Prepare for makepkg
        run: |
          git clone --depth 1 https://gitlab.archlinux.org/archlinux/packaging/packages/llvm.git
          git clone --depth 1 https://gitlab.archlinux.org/archlinux/packaging/packages/compiler-rt.git
          git clone --depth 1 https://gitlab.archlinux.org/archlinux/packaging/packages/clang.git
          git clone --depth 1 https://gitlab.archlinux.org/archlinux/packaging/packages/lld.git
          PKGVERSION=$(grep "pkgver=" llvm/PKGBUILD)
          OLDVERSION="${PKGVERSION#pkgver=}"
          if [ "${{ github.event.inputs.new_llvm_ver }}" != "" ] && [ ${{ github.event.inputs.new_llvm_ver }} != ${OLDVERSION} ]; then
            sh ./modify-llvm-pkgbuild.sh ${{ github.event.inputs.new_llvm_ver }}
            sh ./modify-compiler-rt-pkgbuild.sh ${{ github.event.inputs.new_llvm_ver }}
            sh ./modify-clang-pkgbuild.sh ${{ github.event.inputs.new_llvm_ver }}
            sh ./modify-lld-pkgbuild.sh ${{ github.event.inputs.new_llvm_ver }}
          fi
          echo "USERID=$(id -u $(whoami))" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERID: ''    
      - name: Build llvm
        uses: docker://archlinux:latest
        with:
          entrypoint: '/bin/sh'
          args: ./llvm-build.sh ${{ env.USERID }}
      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: llvm
          path: ${{ github.workspace }}/*.pkg.tar.zst
