name: llvm-build-llvm-libs2

on:
  workflow_run:
    workflows:
      - llvm-build-clang1
    branches:
      - main
    types: 
      - completed
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkount repo
        uses: actions/checkout@v4
      - name: Cleanup
        run: |
          sh ./cleanup.sh
      - name: Prepare for makepkg
        run: |
          git clone --depth 1 https://gitlab.archlinux.org/archlinux/packaging/packages/llvm.git
          sh ./modify-llvm-pkgbuild.sh
          echo "USERID=$(id -u $(whoami))" >> $GITHUB_ENV
          gh run download -n llvm-libs1
          gh run download -n compiler-rt1
          gh run download -n clang1
          gh run download -n lld1
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERID: ''  
      - name: Build llvm
        uses: docker://archlinux:latest
        with:
          entrypoint: '/bin/sh'
          args: ./build-llvm-libs.sh ${{ env.USERID }}
      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: llvm-libs
          path: ${{ github.workspace }}/*.pkg.tar.zst
