name: llvm-build-lld1

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkount repo
        uses: actions/checkout@v4
      - name: Prepare for makepkg
        run: |
          git clone --depth 1 https://gitlab.archlinux.org/archlinux/packaging/packages/lld.git
          sed -i 's/pkgver=17.0.6/pkgver=18.1.3/g' lld/PKGBUILD
          sed -i 's/4ac13125616dc44905b85820aa403d27ec1226329b7f674daeb5f5584c6f0b22/SKIP/g' lld/PKGBUILD
          sed -i 's/b638167da139126ca11917b6880207cc6e8f9d1cbb1a48d87d017f697ef78188/SKIP/g' lld/PKGBUILD
          sed -i 's/9e7535a353aa862730b4ba38df42e06f6856b40c4cc51b57f27b5046dc21d70d/SKIP/g' lld/PKGBUILD
          sed -i 's/807f069c54dc20cb47b21c1f6acafdd9c649f3ae015609040d6182cab01140f4/SKIP/g' lld/PKGBUILD
          sed -i '/patch -Np2/d' lld/PKGBUILD
          echo "USERID=$(id -u $(whoami))" >> $GITHUB_ENV
          gh run download -n llvm-libs1
          gh run download -n compiler-rt1
          gh run download -n clang1
          gh run download -n lld-gcc
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERID: ''
      - name: Build lld
        uses: docker://archlinux:latest
        with:
          entrypoint: '/bin/sh'
          args: ./llvm-build-lld.sh ${{ env.USERID }}
      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: lld1
          path: ${{ github.workspace }}/*.pkg.tar.zst
