name: sample-action

on:
  workflow_dispatch:

env:
  PKGDEST: "/tmp/pkgbuild-llvm-git"

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest    
    steps:
      - name: Checkount repo
        uses: actions/checkout@v3
      - name: Prepare for makepkg
        run: |
          pacman -Syu --noconfirm base-devel sudo
          useradd builder -m -G wheel && echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          curl -L https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=llvm-git -o PKGBUILD
          chown builder -R ..
          chown builder -R /tmp
      - name: Build llvm
        run: su builder -c "yes '' | MAKEFLAGS=\"-j $(nproc)\" makepkg --noconfirm --nocheck -sc"
      - uses: actions/upload-artifact@v3
        with:
          name: llvm-git
          path: ${{ env.PKGDEST }}/*.pkg.tar.zst
        
